const CONFIG = {
  stateName: "Lagos State",
  shortName: "Lagos",
  capital: "Ikeja",
  country: "Nigeria",
  logoUrl: "/lagos-logo.png",
  lgas: [
    "Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Epe",
    "Eti-Osa",
    "Ibeju-Lekki",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Kosofe",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi-Isolo",
    "Shomolu",
    "Surulere",
  ],
};

export default CONFIG;
